---
title: "Visualizing Large Distributions"
author: "Poppy Huang"
date: "04-28-2022"
output:
  html_document:  
    keep_md: true
    toc: true
    toc_float: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
---

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
#install.packages("tidyverse") # run this line once in console to get package
library(tidyverse)
?nycflights13::flights
```

```{r load_data}
# Use this R-Chunk to import all your datasets!
```

## Background

_On-time data for all flights that departed NYC (i.e. JFK, LGA or EWR) in 2013._

## Data Wrangling

```{r tidy_data}
# Use this R-Chunk to clean & wrangle your data!
ggplot(data = flights,
       aes(x = arr_delay)) + geom_bar(color = "blue")
```

## Data Visualization

```{r plot_data}
# Use this R-Chunk to plot & visualize your data!

```

## Conclusions
